os: osx
osx_image: xcode10
before_install:
  - brew update
  - brew upgrade node
  - brew install npm
  - brew install ios-deploy
  - npm install -g appium
  - pip3 install Appium-Python-Client
  #- python setup.py install
#language: python
#python:
#  - "3.6"
# command to install dependencies
#install:
#  - pip install -r requirements.txt
# command to run tests
script:
  - echo "\e[31m[INFO] Starting appium server\e[0m"
  - appium &
  - echo "\e[31m[INFO] Appium server started\e[0m"
  - sleep 7s
  - cd /Users/travis/build/ArsenUa/TestMobileProject
  - sleep 7s
  - echo "\e[31m[INFO] Starting testsr\e[0m"
  - python3 simulatorTest.py
  - echo "\e[31m[INFO] Finished testsr\e[0m"
